project_id: "sabs-1000"
region: "asia-south1"

# Buckets (created by Terraform)
data_bucket: "mlapp-dev-data-sabs-1000"
artifacts_bucket: "mlapp-dev-artifacts-sabs-1000"

# BigQuery
dataset_id: "training_dataset_dev"
table_id: "features_table"

# Schema
feature_columns:
  - "f1"
  - "f2"
  - "f3"
  - "f4"
  - "f5"
target_column: "T"

# GCS paths (versioned)
data_gcs_prefix: "data"
models_gcs_prefix: "models"
model_filename: "model.joblib"
latest_subfolder: "latest"

# Infra outputs (from Terraform / cmd.md)
artifact_repo_url: "asia-south1-docker.pkg.dev/sabs-1000/mlapp-dev-repo"
cicd_service_account: "mlapp-dev-cicd@sabs-1000.iam.gserviceaccount.com"
runtime_service_account: "mlapp-dev-runtime@sabs-1000.iam.gserviceaccount.com"
